### ISSUE TITLE
it seems only change theme will case some problem?

### ISSUE THREAD

**Issue by ghost** [maldoinc/plasma-theme-switcher#1]
just switch theme to dark or light theme not work for GTK application,must change color scheme can work.
KDE 5.20

**Comment by maldoinc** [comment]
Thanks for reporting this. Unfortunately I use no GTK apps on my syste, but I will take a look at this.

**Comment by ghost** [comment]
> 
> 
> Thanks for reporting this. Unfortunately I use no GTK apps on my syste, but I will take a look at this.

It seems a bug in kde not yours,already had some guy reported.
